<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AutomaticPaymentGatewaysTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('automatic_payment_gateways')->delete();
        
        \DB::table('automatic_payment_gateways')->insert(array (
            0 => 
            array (
                'id' => 1,
                'uid' => '9C1E8F9209B0988DCF8E',
                'name' => 'Iyzico',
                'slug' => 'iyzico',
                'logo_id' => NULL,
                'currency' => 'TRY',
                'exchange_rate' => 24.0,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 24.0,
                'deposit_max_amount' => 900000.0,
                'settings' => '{"api_key":"","secret_key":"","env":"sandbox","sandbox_link":"https:\\/\\/sandbox-api.iyzipay.com","production_link":"https:\\/\\/api.iyzipay.com"}',
                'is_active' => 0,
                'country' => 'tr',
            ),
            1 => 
            array (
                'id' => 2,
                'uid' => '65952467607D7AEB3EE4',
                'name' => 'Genie Business',
                'slug' => 'genie-business',
                'logo_id' => NULL,
                'currency' => 'LKR',
                'exchange_rate' => 297.0,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 300.0,
                'deposit_max_amount' => 900000.0,
                'settings' => '{"app_key":"","env":"sandbox","sandbox_link":"https:\\/\\/api.uat.geniebiz.lk","production_link":"https:\\/\\/api.geniebiz.lk"}',
                'is_active' => 0,
                'country' => 'lk',
            ),
            2 => 
            array (
                'id' => 3,
                'uid' => '03E54C5D7B8DCE8E147D',
                'name' => 'Asaas',
                'slug' => 'asaas',
                'logo_id' => NULL,
                'currency' => 'BRL',
                'exchange_rate' => 5.0,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 10.0,
                'deposit_max_amount' => 900000.0,
                'settings' => '{"api_key":"","access_token":null,"env":"sandbox","sandbox_link":"https:\\/\\/sandbox.asaas.com\\/api\\/v3","production_link":"https:\\/\\/wwww.asaas.com\\/api\\/v3"}',
                'is_active' => 0,
                'country' => 'br',
            ),
            3 => 
            array (
                'id' => 4,
                'uid' => '2BD5219432C5CF02E318',
                'name' => 'Ecpay',
                'slug' => 'ecpay',
                'logo_id' => NULL,
                'currency' => 'TWD',
                'exchange_rate' => 62.0,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 62.0,
                'deposit_max_amount' => 90000.0,
                'settings' => '{"hash_key":"","hash_iv":"","merchant_id":"","env":"sandbox","sandbox_link":"https:\\/\\/payment-stage.ecpay.com.tw\\/Cashier\\/AioCheckOut\\/V5","production_link":"https:\\/\\/payment.ecpay.com.tw\\/Cashier\\/AioCheckOut\\/V5"}',
                'is_active' => 0,
                'country' => 'tw',
            ),
            4 => 
            array (
                'id' => 5,
                'uid' => '51BF233182120CDC61D9',
                'name' => 'Fast Pay',
                'slug' => 'fastpay',
                'logo_id' => NULL,
                'currency' => 'IQD',
                'exchange_rate' => 1310.0,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 1310.0,
                'deposit_max_amount' => 900000.0,
                'settings' => '{"merchant_mobile_no":"","store_password":"","env":"sandbox","sandbox_link":"https:\\/\\/dev.fast-pay.cash\\/","production_link":"https:\\/\\/secure.fast-pay.cash\\/"}',
                'is_active' => 0,
                'country' => 'iq',
            ),
            5 => 
            array (
                'id' => 6,
                'uid' => '0DD92FEA338DE1C0314C',
                'name' => 'Freekassa',
                'slug' => 'freekassa',
                'logo_id' => NULL,
                'currency' => 'RUB',
                'exchange_rate' => 84.0,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 40.0,
                'deposit_max_amount' => 45000.0,
                'settings' => '{"shop_id":"","merchant_api_key":"","merchant_secret":"","request_link":"https:\\/\\/pay.freekassa.ru\\/"}',
                'is_active' => 0,
                'country' => 'ru',
            ),
            6 => 
            array (
                'id' => 7,
                'uid' => 'DEF3FDCB8F62A38FC138',
                'name' => 'Duitku',
                'slug' => 'duitku',
                'logo_id' => NULL,
                'currency' => 'IDR',
                'exchange_rate' => 14900.0,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 14900.0,
                'deposit_max_amount' => 900000.0,
                'settings' => '{"api_key":"","merchant_code":"","env":"sandbox","sandbox_link":"https:\\/\\/sandbox.duitku.com\\/","production_link":"https:\\/\\/passport.duitku.com\\/"}',
                'is_active' => 0,
                'country' => 'id',
            ),
            7 => 
            array (
                'id' => 8,
                'uid' => '8C3202830DE171146794',
                'name' => 'Paymob PK',
                'slug' => 'paymob-pk',
                'logo_id' => NULL,
                'currency' => 'PKR',
                'exchange_rate' => 290.0,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 1.0,
                'deposit_max_amount' => 100.0,
                'settings' => '{"api_key":"","hmac_hash":null,"merchant_id":null,"iframe_id":null,"integration_id":null,"env":"sandbox","auth_link":"https:\\/\\/pakistan.paymob.com\\/api\\/auth\\/tokens","order_link":"https:\\/\\/pakistan.paymob.com\\/api\\/ecommerce\\/orders","payment_link":"https:\\/\\/pakistan.paymob.com\\/api\\/acceptance\\/payment_keys","iframe_link":"https:\\/\\/pakistan.paymob.com\\/api\\/acceptance\\/iframes"}',
                'is_active' => 0,
                'country' => 'pk',
            ),
            8 => 
            array (
                'id' => 9,
                'uid' => 'ABF607881482DBAE74DE',
                'name' => 'cPay',
                'slug' => 'cpay',
                'logo_id' => NULL,
                'currency' => 'MKD',
                'exchange_rate' => 58.0,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 60.0,
                'deposit_max_amount' => 900000.0,
                'settings' => '{"merchant_id":null,"merchant_name":null,"password":null,"request_link":"https:\\/\\/www.cpay.com.mk\\/client\\/Page\\/default.aspx?xml_id=\\/mk-MK\\/.loginToPay\\/.simple\\/"}',
                'is_active' => 0,
                'country' => 'mk',
            ),
            9 => 
            array (
                'id' => 10,
                'uid' => '21B6B5B855047563BB7F',
                'name' => 'NowPayments.io',
                'slug' => 'nowpayments',
                'logo_id' => NULL,
                'currency' => 'USDTERC20',
                'exchange_rate' => 1.1,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 1.1,
                'deposit_max_amount' => 5000.0,
                'settings' => '{"api_key":"","ipn_secret":"","env":"sandbox","sandbox_link":"https:\\/\\/api-sandbox.nowpayments.io\\/v1\\/","production_link":"https:\\/\\/api.nowpayments.io\\/v1\\/"}',
                'is_active' => 0,
                'country' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'uid' => '13D16CA6720F9B28B638',
                'name' => 'PayPal',
                'slug' => 'paypal',
                'logo_id' => NULL,
                'currency' => 'USD',
                'exchange_rate' => 1.0,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 1.0,
                'deposit_max_amount' => 5000.0,
                'settings' => '{"client_id":"","client_secret":"","env":"sandbox","sandbox_link":"https:\\/\\/www.sandbox.paypal.com\\/cgi-bin\\/webscr\\/","production_link":"https:\\/\\/www.paypal.com\\/cgi-bin\\/webscr\\/"}',
                'is_active' => 0,
                'country' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'uid' => 'D238A895792F8F7700BA',
                'name' => 'Stripe',
                'slug' => 'stripe',
                'logo_id' => NULL,
                'currency' => 'USD',
                'exchange_rate' => 1.0,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 1.0,
                'deposit_max_amount' => 5000.0,
                'settings' => '{"public_key":"","secret_key":""}',
                'is_active' => 0,
                'country' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'uid' => '4BC29362EE0DA7810874',
                'name' => 'Paystack',
                'slug' => 'paystack',
                'logo_id' => NULL,
                'currency' => 'NGN',
                'exchange_rate' => 755.0,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 800.0,
                'deposit_max_amount' => 380000.0,
                'settings' => '{"public_key":"","secret_key":"","request_link":"https:\\/\\/api.paystack.co"}',
                'is_active' => 0,
                'country' => 'ng',
            ),
            13 => 
            array (
                'id' => 14,
                'uid' => '24CDDD08816EF46C5734',
                'name' => 'Cashfree',
                'slug' => 'cashfree',
                'logo_id' => NULL,
                'currency' => 'INR',
                'exchange_rate' => 83.0,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 90.0,
                'deposit_max_amount' => 420000.0,
                'settings' => '{"app_id":"","secret_key":"","env":"sandbox","sandbox_link":"https:\\/\\/sandbox.cashfree.com\\/","production_link":"https:\\/\\/api.cashfree.com\\/"}',
                'is_active' => 0,
                'country' => 'in',
            ),
            14 => 
            array (
                'id' => 15,
                'uid' => 'C52531421BE167414315',
                'name' => 'Xendit',
                'slug' => 'xendit',
                'logo_id' => NULL,
                'currency' => 'IDR',
                'exchange_rate' => 15100.0,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 15100.0,
                'deposit_max_amount' => 200000.0,
                'settings' => '{"public_key":"","secret_key":""}',
                'is_active' => 0,
                'country' => 'id',
            ),
            15 => 
            array (
                'id' => 16,
                'uid' => '262A838E10EB6BD1D7E4',
                'name' => 'Flutterwave',
                'slug' => 'flutterwave',
                'logo_id' => NULL,
                'currency' => 'NGN',
                'exchange_rate' => 755.0,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 800.0,
                'deposit_max_amount' => 900000.0,
                'settings' => '{"public_key":"","secret_key":"","encryption_key":"","env":"sandbox"}',
                'is_active' => 0,
                'country' => 'ng',
            ),
            16 => 
            array (
                'id' => 17,
                'uid' => 'B68A8B1A49591A554D56',
                'name' => 'VNPay',
                'slug' => 'vnpay',
                'logo_id' => NULL,
                'currency' => 'VND',
                'exchange_rate' => 23600.0,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 23600.0,
                'deposit_max_amount' => 900000.0,
                'settings' => '{"tmn_code":"","hash_secret":"","env":"sandbox","sandbox_link":"http:\\/\\/sandbox.vnpayment.vn\\/paymentv2\\/vpcpay.html","production_link":"https:\\/\\/sandbox.vnpayment.vn\\/merchant_webapi\\/merchant.html"}',
                'is_active' => 0,
                'country' => 'vn',
            ),
            17 => 
            array (
                'id' => 18,
                'uid' => '972F478DD2DD39C993EE',
                'name' => 'Paymob EG',
                'slug' => 'paymob',
                'logo_id' => NULL,
                'currency' => 'EGP',
                'exchange_rate' => 32.0,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 32.0,
                'deposit_max_amount' => 900000.0,
                'settings' => '{"api_key":null,"hmac_hash":null,"merchant_id":null,"iframe_id":null,"integration_id":null,"env":"sandbox","auth_link":"https:\\/\\/accept.paymob.com\\/api\\/auth\\/tokens","order_link":"https:\\/\\/accept.paymob.com\\/api\\/ecommerce\\/orders","payment_link":"https:\\/\\/accept.paymob.com\\/api\\/acceptance\\/payment_keys"}',
                'is_active' => 0,
                'country' => 'eg',
            ),
            18 => 
            array (
                'id' => 19,
                'uid' => '99782CD117D4337A0A97',
                'name' => 'Mercadopago',
                'slug' => 'mercadopago',
                'logo_id' => NULL,
                'currency' => 'BRL',
                'exchange_rate' => 4.8,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 4.8,
                'deposit_max_amount' => 900000.0,
                'settings' => '{"public_key":"","access_token":"","env":"sandbox"}',
                'is_active' => 0,
                'country' => 'br',
            ),
            19 => 
            array (
                'id' => 20,
                'uid' => '3131A6F485B6AFFEF58B',
                'name' => 'Paytabs',
                'slug' => 'paytabs',
                'logo_id' => NULL,
                'currency' => 'SAR',
                'exchange_rate' => 3.8,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 3.8,
                'deposit_max_amount' => 900000.0,
                'settings' => '{"profile_id":"","server_key":"","region":"GLOBAL"}',
                'is_active' => 0,
                'country' => 'sa',
            ),
            20 => 
            array (
                'id' => 21,
                'uid' => '55F386845EA73CC6EB70',
                'name' => 'Razorpay',
                'slug' => 'razorpay',
                'logo_id' => NULL,
                'currency' => 'INR',
                'exchange_rate' => 83.0,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 83.0,
                'deposit_max_amount' => 900000.0,
                'settings' => '{"key_id":"","key_secret":""}',
                'is_active' => 0,
                'country' => 'in',
            ),
            21 => 
            array (
                'id' => 22,
                'uid' => 'CE82776D8EAF5A614C19',
                'name' => 'Mollie',
                'slug' => 'mollie',
                'logo_id' => NULL,
                'currency' => 'USD',
                'exchange_rate' => 1.0,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 1.0,
                'deposit_max_amount' => 5000.0,
                'settings' => '{"key":""}',
                'is_active' => 0,
                'country' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'uid' => '2598E612A51DEF5A7A20',
                'name' => 'PayTR',
                'slug' => 'paytr',
                'logo_id' => NULL,
                'currency' => 'TRY',
                'exchange_rate' => 27.0,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 27.0,
                'deposit_max_amount' => 900000.0,
                'settings' => '{"merchant_id":null,"merchant_key":null,"merchant_salt":null,"env":"sandbox","token_link":"https:\\/\\/www.paytr.com\\/odeme\\/api\\/get-token","iframe_link":"https:\\/\\/www.paytr.com\\/odeme\\/guvenli\\/iframe_token"}',
                'is_active' => 0,
                'country' => 'tr',
            ),
            23 => 
            array (
                'id' => 24,
                'uid' => 'DDFA14DDDF95082AC030',
                'name' => 'Jazzcash',
                'slug' => 'jazzcash',
                'logo_id' => NULL,
                'currency' => 'PKR',
                'exchange_rate' => 287.0,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 287.0,
                'deposit_max_amount' => 900000.0,
                'settings' => '{"merchant_id":"","password":"","integerity_salt":"","env":"sandbox","return_link":"http:\\/\\/localhost\\/demo\\/callback\\/jazzcash","sandbox_link":"https:\\/\\/sandbox.jazzcash.com.pk\\/CustomerPortal\\/transactionmanagement\\/merchantform","production_link":"https:\\/\\/payments.jazzcash.com.pk\\/CustomerPortal\\/transactionmanagement\\/merchantform"}',
                'is_active' => 0,
                'country' => 'pk',
            ),
            24 => 
            array (
                'id' => 25,
                'uid' => '1E934EFA03D8C3B6F177',
                'name' => 'YouCanPay',
                'slug' => 'youcanpay',
                'logo_id' => NULL,
                'currency' => 'MAD',
                'exchange_rate' => 10.0,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 10.0,
                'deposit_max_amount' => 900000.0,
                'settings' => '{"public_key":"","private_key":""}',
                'is_active' => 0,
                'country' => 'ma',
            ),
            25 => 
            array (
                'id' => 26,
                'uid' => '2415450D8225605AF2EB',
                'name' => 'Epoint.az',
                'slug' => 'epoint',
                'logo_id' => NULL,
                'currency' => 'AZN',
                'exchange_rate' => 1.7,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 1.7,
                'deposit_max_amount' => 900000.0,
                'settings' => '{"public_key":"","private_key":""}',
                'is_active' => 0,
                'country' => 'az',
            ),
            26 => 
            array (
                'id' => 27,
                'uid' => '46DF38EC8B0E1D31BD9A',
                'name' => 'CamPay',
                'slug' => 'campay',
                'logo_id' => NULL,
                'currency' => 'XAF',
                'exchange_rate' => 605.0,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 1200.0,
                'deposit_max_amount' => 900000.0,
                'settings' => '{"app_username":"","app_password":"","env":"sandbox","sandbox_link":"https:\\/\\/demo.campay.net","production_link":"https:\\/\\/www.campay.net"}',
                'is_active' => 0,
                'country' => 'cm',
            ),
            27 => 
            array (
                'id' => 28,
                'uid' => '95A9BB86004AECF9A451',
                'name' => 'Robokassa',
                'slug' => 'robokassa',
                'logo_id' => NULL,
                'currency' => 'RUB',
                'exchange_rate' => 84.0,
                'fixed_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'percentage_fee' => '{"deposit":"0","gigs":"0","projects":"0","bids":"0"}',
                'deposit_min_amount' => 84.0,
                'deposit_max_amount' => 900000.0,
                'settings' => '{"mrh_login":null,"mrh_pass1":null,"mrh_pass2":null,"inv_id":null,"env":"sandbox","request_link":"https:\\/\\/auth.robokassa.ru\\/Merchant\\/Index.aspx"}',
                'is_active' => 0,
                'country' => 'ru',
            ),
        ));
        
        
    }
}